from flask import Flask
from flask_sqlalchemy import SQLAlchemy
app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///onlineshop.db?charset=utf8mb4'
db = SQLAlchemy()
db.init_app(app)

items = [
    {
        "id": "0001",
        "name": "Mealworms(Small)",
        "short_name": "mealworms",
        "image_link": "../static/assets/item_imgs/mealworms.jpg",
        "price": "3.99",
        "ratings": "⭐⭐⭐⭐",
        "reviews": "523",
        "short_desc": "Small mealworms. Each order of mealworms comes in a quantity of 50 worms.",
        "quantity": "50",
        "description": "Mealworms are a fantastic source of essential nutrients for reptiles. They offer several benefits that contribute to your pet’s overall health, growth, and vitality. Mealworms have a high protein content, beneficial fats, are nutrient-rich, provide mental stimulation and are easy to find and convenient. Remember that while mealworms are beneficial, they should not be the sole component of your reptile’s diet. Ensure a balanced nutritional intake by incorporating a variety of feeder insects, leafy greens, and commercially available reptile pellets.",
        "cart_name": "Mealworms(Small) - 50 worms",
    },
    {
        "id": "0002",
        "name": "Mealworms(Medium)",
        "short_name": "mealworms",
        "image_link": "../static/assets/item_imgs/mealworms.jpg",
        "price": "4.99",
        "ratings": "⭐⭐⭐⭐⭐",
        "reviews": "879",
        "short_desc": "Small mealworms. Each order of mealworms comes in a quantity of 50 worms.",
        "quantity": "50",
        "description": "Mealworms are a fantastic source of essential nutrients for reptiles. They offer several benefits that contribute to your pet’s overall health, growth, and vitality. Mealworms have a high protein content, beneficial fats, are nutrient-rich, provide mental stimulation and are easy to find and convenient. Remember that while mealworms are beneficial, they should not be the sole component of your reptile’s diet. Ensure a balanced nutritional intake by incorporating a variety of feeder insects, leafy greens, and commercially available reptile pellets.",
        "cart_name": "Mealworms(Medium) - 50 worms",
    },
    {
        "id": "0003",
        "name": "Mealworms(Large)",
        "short_name": "mealworms",
        "image_link": "../static/assets/item_imgs/mealworms.jpg",
        "price": "5.99",
        "ratings": "⭐⭐⭐⭐⭐",
        "reviews": "1003",
        "short_desc": "Large mealworms. Each order of mealworms comes in a quantity of 50 worms.",
        "quantity": "50",
        "description": "Mealworms are a fantastic source of essential nutrients for reptiles. They offer several benefits that contribute to your pet’s overall health, growth, and vitality. Mealworms have a high protein content, beneficial fats, are nutrient-rich, provide mental stimulation and are easy to find and convenient. Remember that while mealworms are beneficial, they should not be the sole component of your reptile’s diet. Ensure a balanced nutritional intake by incorporating a variety of feeder insects, leafy greens, and commercially available reptile pellets.",
        "cart_name": "Mealworms(Large) - 50 worms",
    },
    {
        "id": "0004",
        "name": "Superworms(Small)",
        "short_name": "superworms",
        "image_link": "../static/assets/item_imgs/superworms.jpg",
        "price": "4.99",
        "ratings": "⭐⭐⭐⭐⭐",
        "reviews": "1203",
        "short_desc": "Small superworms. Each order of superworms comes in a quantity of 50 worms.",
        "quantity": "50",
        "description": "Superworms offer several benefits for reptiles, including bearded dragons. Superworms have a high protein content, essential fat content, vitamins and minerals, provide gut loading potential, are a hydration source, provide enrichment and hunting behavior, are suitable for various reptiles, and are easy to store. Remember to feed superworms in moderation and consult with a veterinarian to ensure your reptile’s dietary needs are met.",
        "cart_name": "Superworms(Small) - 50 worms",
    },
    {
        "id": "0005",
        "name": "Superworms(Medium)",
        "short_name": "superworms",
        "image_link": "../static/assets/item_imgs/superworms.jpg",
        "price": "5.99",
        "ratings": "⭐⭐⭐⭐⭐",
        "reviews": "1112",
        "short_desc": "Medium superworms. Each order of superworms comes in a quantity of 50 worms.",
        "quantity": "50",
        "description": "Superworms offer several benefits for reptiles, including bearded dragons. Superworms have a high protein content, essential fat content, vitamins and minerals, provide gut loading potential, are a hydration source, provide enrichment and hunting behavior, are suitable for various reptiles, and are easy to store. Remember to feed superworms in moderation and consult with a veterinarian to ensure your reptile’s dietary needs are met.",
        "cart_name": "Superworms(Medium) - 50 worms",
    },
    {
        "id": "0006",
        "name": "Superworms(Large)",
        "short_name": "superworms",
        "image_link": "../static/assets/item_imgs/superworms.jpg",
        "price": "6.99",
        "ratings": "⭐⭐⭐⭐⭐",
        "reviews": "1562",
        "short_desc": "Large superworms. Each order of superworms comes in a quantity of 50 worms.",
        "quantity": "50",
        "description": "Superworms offer several benefits for reptiles, including bearded dragons. Superworms have a high protein content, essential fat content, vitamins and minerals, provide gut loading potential, are a hydration source, provide enrichment and hunting behavior, are suitable for various reptiles, and are easy to store. Remember to feed superworms in moderation and consult with a veterinarian to ensure your reptile’s dietary needs are met.",
        "cart_name": "Superworms(Large) - 50 worms",
    },
    {
        "id": "0007",
        "name": "Crickets(Small)",
        "short_name": "crickets",
        "image_link": "../static/assets/item_imgs/crickets.jpg",
        "price": "4.99",
        "ratings": "⭐⭐⭐",
        "reviews": "792",
        "short_desc": "Chirping crickets. Each order of crickets comes in a quantity of 25 crickets.",
        "quantity": "25",
        "description": "Crickets (genera Gryllus and Acheta) are popular feeder insects for a variety of pet invertebrates, amphibians, and reptiles. They offer a balanced nutritional profile, containing moderate amounts of protein, fat, and fiber. Among reptile enthusiasts, brown house crickets (Acheta domesticus) have been the #1 most popular feeder insect for years. When feeding your reptiles, it’s essential to consider the overall nutritional balance. You can enhance the crickets’ nutritional value by gut-loading them with high-quality food before offering them to your scaly companions. Remember, a well-rounded diet contributes to the health and vitality of your reptiles!",
        "cart_name": "Crickets(Small) - 25 crickets",
    },
        {
        "id": "0008",
        "name": "Crickets(Medium)",
        "short_name": "crickets",
        "image_link": "../static/assets/item_imgs/crickets.jpg",
        "price": "5.99",
        "ratings": "⭐⭐⭐⭐⭐",
        "reviews": "842",
        "short_desc": "Chirping crickets. Each order of crickets comes in a quantity of 25 crickets.",
        "quantity": "25",
        "description": "Crickets (genera Gryllus and Acheta) are popular feeder insects for a variety of pet invertebrates, amphibians, and reptiles. They offer a balanced nutritional profile, containing moderate amounts of protein, fat, and fiber. Among reptile enthusiasts, brown house crickets (Acheta domesticus) have been the #1 most popular feeder insect for years. When feeding your reptiles, it’s essential to consider the overall nutritional balance. You can enhance the crickets’ nutritional value by gut-loading them with high-quality food before offering them to your scaly companions. Remember, a well-rounded diet contributes to the health and vitality of your reptiles!",
        "cart_name": "Crickets(Medium) - 25 crickets",
    },
        {
        "id": "0009",
        "name": "Crickets(Large)",
        "short_name": "crickets",
        "image_link": "../static/assets/item_imgs/crickets.jpg",
        "price": "6.99",
        "ratings": "⭐⭐⭐⭐",
        "reviews": "329",
        "short_desc": "Chirping crickets. Each order of crickets comes in a quantity of 25 crickets.",
        "quantity": "25",
        "description": "Crickets (genera Gryllus and Acheta) are popular feeder insects for a variety of pet invertebrates, amphibians, and reptiles. They offer a balanced nutritional profile, containing moderate amounts of protein, fat, and fiber. Among reptile enthusiasts, brown house crickets (Acheta domesticus) have been the #1 most popular feeder insect for years. When feeding your reptiles, it’s essential to consider the overall nutritional balance. You can enhance the crickets’ nutritional value by gut-loading them with high-quality food before offering them to your scaly companions. Remember, a well-rounded diet contributes to the health and vitality of your reptiles!",
        "cart_name": "Crickets(Large) - 25 crickets",
    },
        {
        "id": "0010",
        "name": "Dubia Roach(Male)",
        "short_name": "dubia roaches",
        "image_link": "../static/assets/item_imgs/dubia_male.jpg",
        "price": "1.99",
        "ratings": "⭐⭐⭐⭐",
        "reviews": "235",
        "short_desc": "Male dubia roaches. Sold in quantities of four.",
        "quantity": "4",
        "description": "Dubia roaches, those unassuming cave insects with a remarkable nutritional profile, have emerged as a popular choice for reptile enthusiasts seeking to provide their scaly companions with a natural and balanced diet. Let’s explore the benefits of feeding Dubia roaches to reptiles. Dubia roaches provide high-quality protein, optimal calcium-to-phosphorus ratio, beneficial fats, and hydration. By incorporating Dubia roaches into the diet of your reptile companions, you’re providing them with a natural and nutrient-rich feast.",
        "cart_name": "Dubia Roach(Male) - 4 roaches",
    },
        {
        "id": "0011",
        "name": "Dubia Roach(Female)",
        "short_name": "dubia roaches",
        "image_link": "../static/assets/item_imgs/dubia_female.jpg",
        "price": "2.99",
        "ratings": "⭐⭐⭐⭐",
        "reviews": "365",
        "short_desc": "female dubia roaches. Sold in quantities of four.",
        "quantity": "4",
        "description": "Dubia roaches, those unassuming cave insects with a remarkable nutritional profile, have emerged as a popular choice for reptile enthusiasts seeking to provide their scaly companions with a natural and balanced diet. Let’s explore the benefits of feeding Dubia roaches to reptiles. Dubia roaches provide high-quality protein, optimal calcium-to-phosphorus ratio, beneficial fats, and hydration. By incorporating Dubia roaches into the diet of your reptile companions, you’re providing them with a natural and nutrient-rich feast.",
        "cart_name": "Dubia Roach(Female) - 4 roaches",
    },
        {
        "id": "0012",
        "name": "Dubia Roach(Pair)",
        "short_name": "dubia roaches",
        "image_link": "../static/assets/item_imgs/dubia_male_female.jpg",
        "price": "4.99",
        "ratings": "⭐⭐⭐⭐⭐",
        "reviews": "1068",
        "short_desc": "An order of both male and female dubia roaches. Orders contain six male and six female roaches.",
        "quantity": "12",
        "description": "Dubia roaches, those unassuming cave insects with a remarkable nutritional profile, have emerged as a popular choice for reptile enthusiasts seeking to provide their scaly companions with a natural and balanced diet. Let’s explore the benefits of feeding Dubia roaches to reptiles. Dubia roaches provide high-quality protein, optimal calcium-to-phosphorus ratio, beneficial fats, and hydration. By incorporating Dubia roaches into the diet of your reptile companions, you’re providing them with a natural and nutrient-rich feast.",
        "cart_name": "Dubia Roach(Pair) - 12 roaches",
    },
        {
        "id": "0013",
        "name": "Hornworms",
        "short_name": "hornworms",
        "image_link": "../static/assets/item_imgs/hornworm.jpg",
        "price": "2.25",
        "ratings": "⭐⭐⭐⭐⭐",
        "reviews": "665",
        "short_desc": "Treat your little friends with a nice delicious snack! Hornworms are sold individually.",
        "quantity": "1",
        "description": "Hornworms, those plump and vibrant caterpillars, offer a nutritious feast for reptiles. Let’s delve into the benefits of incorporating these wiggly wonders into your reptile’s diet. Hornworms are nutrient-rich, providing protein, amino acids, vitamins and minerals. Hornworms also provide, hydration, and are easy to care for. Although hornworms lack a balanced calcium-to phosphorus ratio, they can still be fed consistently. It is critical to dust the with high-quality calcium powered before offering them to your reptile. Remember, variety is key!",
        "cart_name": "Hornworms - 1 worm",
    },
        {
        "id": "0014",
        "name": "Silkworms",
        "short_name": "silkworms",
        "image_link": "../static/assets/item_imgs/silkworms.jpg",
        "price": "4.99",
        "ratings": "⭐⭐⭐⭐",
        "reviews": "437",
        "short_desc": "Silkworms. Our silkworms are sold in quantities of 25 per order.",
        "quantity": "25",
        "description": "Silkworms are indeed a fascinating choice as feeder insects for your pet reptiles. Silkworms are high in moisture, which can be beneficial for hydration. They are lower in protein compared to some other feeders like dubia roaches, crickets, BSFL larvae, superworms, mealworms, and waxworms. Silkworms are extremely low in fat. Their calcium:phosphorus (Ca:P) ratio is solid, which is essential for reptile health.  Silkworms’ low fat and protein content makes them relatively low-calorie per worm. They can be useful for helping obese reptiles lose weight. Their soft bodies make silkworms easier to chew and digest compared to tougher feeders like roaches and mealworms. Remember, silkworms are not just for silk production—they can also be a valuable part of your reptiles diet! 🐍🦎🍽️",
        "cart_name": "Silkworms - 25 worms",
    },
        {
        "id": "0015",
        "name": "Red Runner Roaches",
        "short_name": "red runner roaches",
        "image_link": "../static/assets/item_imgs/red_runner_roach.jpg",
        "price": "4.99",
        "ratings": "⭐⭐⭐⭐",
        "reviews": "109",
        "short_desc": "Red Runner Roaches! No they are not your city roaches. Sold in quantities of 20 per order.",
        "quantity": "20",
        "description": "Red runner roaches (Blatta lateralis) are an excellent choice as feeder insects for reptiles. Red runner roaches range from approximately 1/8 inch as newborn nymphs to 1 inch as adults. This size is comparable to crickets. Red runners are suitable for smaller reptiles, amphibians, and arachnids. Their quick movement and comparable size make them a good alternative to crickets. Their skittery movement often triggers an enthusiastic feeding response. Unlike some other roaches, red runners have a soft shell. Remember, providing a variety of feeder insects ensures balanced nutrition for your reptiles. Red runner roaches can be a valuable addition to your rotation!",
        "cart_name": "Red Runner Roaches - 20 roaches",
    },
        {
        "id": "0016",
        "name": "Waxworms",
        "short_name": "waxworms",
        "image_link": "../static/assets/item_imgs/waxworms.jpg",
        "price": "4.99",
        "ratings": "⭐⭐⭐",
        "reviews": "168",
        "short_desc": "Treat your little friend to some waxworms. Our waxworms are sold in quantities of 50 per order.",
        "quantity": "50",
        "description": "Crickets (genera Gryllus and Acheta) are popular feeder insects for a variety of pet invertebrates, amphibians, and reptiles. They offer a balanced nutritional profile, containing moderate amounts of protein, fat, and fiber. Among reptile enthusiasts, brown house crickets (Acheta domesticus) have been the #1 most popular feeder insect for years. When feeding your reptiles, it’s essential to consider the overall nutritional balance. You can enhance the crickets’ nutritional value by gut-loading them with high-quality food before offering them to your scaly companions. Remember, a well-rounded diet contributes to the health and vitality of your reptiles!",
        "cart_name": "Waxworms - 50 worms",
    },
        {
        "id": "0017",
        "name": "Soldier Fly Larva",
        "short_name": "soldier fly larva",
        "image_link": "../static/assets/item_imgs/soldier_fly_larva.jpg",
        "price": "4.99",
        "ratings": "⭐⭐⭐",
        "reviews": "89",
        "short_desc": "Grubs for our buds! Soldier fly larva are sold in quantities of 50 per order.",
        "quantity": "50",
        "description": "Black Soldier Fly Larvae (BSFL) are a fantastic choice as feeder insects for various reptiles, amphibians, birds, and invertebrates. BSFL are a great source of protein, are naturally high in calcium, have a moderate fat content and are easier to digest than some other feeders like mealworms, and their soft bodies make them enticing even for picky eaters. The balanced calcium to phosphorus ratio in BSFL helps prevent and reverse Metabolic Bone Disease in reptiles. BSFL are efficient decomposers of organic waste, making them beneficial for the environment. BSFL are suitable for bearded dragons, geckos, chameleons, turtles, and most pet reptiles or amphibians.",
        "cart_name": "Soldier Fly Larva - 50 grubs",
    },
        {
        "id": "0018",
        "name": "Dried Mealworms",
        "short_name": "mealworms",
        "image_link": "../static/assets/item_imgs/dried_mealworms.jpg",
        "price": "10.49",
        "ratings": "⭐⭐⭐⭐",
        "reviews": "201",
        "short_desc": "Dried mealworms sold in 2 lb. containers.",
        "quantity": "2 lb per container",
        "description": "Mealworms are a fantastic source of essential nutrients for reptiles. They offer several benefits that contribute to your pet’s overall health, growth, and vitality. Mealworms have a high protein content, beneficial fats, are nutrient-rich, provide mental stimulation and are easy to find and convenient. Remember that while mealworms are beneficial, they should not be the sole component of your reptile’s diet. Ensure a balanced nutritional intake by incorporating a variety of feeder insects, leafy greens, and commercially available reptile pellets.",
        "cart_name": "Dried Mealworms - 2 lb. container",
    },
]


def product_table_values():
    """Dictionary on this page is used to create the products database table. Could alternatively just created list to render shop instead of database table."""
    item_list = []
    for item in items:
        value_list = []
        for key, value in item.items():
            value_list.append(value)

        item_list.append(value_list)
        value_list = []
    return item_list


def populate_product_table(table):
    """List values returned from product_table_values are used to populate the Product table if it does not already exist."""
    try:
        list_of_products = product_table_values()
        for product in list_of_products:
            new_product = table(
                item_id = product[0],
                productname = product[1],
                short_name = product[2],
                image_link = product[3],
                price = product[4],
                rating = product[5],
                reviews = product[6],
                short_desc = product[7],
                quantity = product[8],
                description = product[9],
                cart_name = product[10],
            )
            with app.app_context():
                db.session.add(new_product)
                db.session.commit()
    except: 
        pass